prob(p00,
     [upFrom(a,d), upFrom(b,e), upFrom(c,f),
      upFrom(d,g), upFrom(e,h), upFrom(f,i),
      downFrom(g,d), downFrom(h,e), downFrom(i,f),
      downFrom(d,a), downFrom(e,b), downFrom(f,c),
      leftFrom(a,b), leftFrom(b,c),
      leftFrom(d,e), leftFrom(e,f),
      leftFrom(g,h), leftFrom(h,i),
      rightFrom(b,a), rightFrom(c,b),
      rightFrom(e,d), rightFrom(f,e),
      rightFrom(h,g), rightFrom(i,h),
      tileAt(t1, a), spaceAt(b), tileAt(t2, c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, f),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)],
     [spaceAt(a), tileAt(t1, b), tileAt(t2, c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, f),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)]).


prob(p01, 
     [upFrom(a,d), upFrom(b,e), upFrom(c,f),
      upFrom(d,g), upFrom(e,h), upFrom(f,i),
      downFrom(g,d), downFrom(h,e), downFrom(i,f),
      downFrom(d,a), downFrom(e,b), downFrom(f,c),
      leftFrom(a,b), leftFrom(b,c),
      leftFrom(d,e), leftFrom(e,f),
      leftFrom(g,h), leftFrom(h,i),
      rightFrom(b,a), rightFrom(c,b),
      rightFrom(e,d), rightFrom(f,e),
      rightFrom(h,g), rightFrom(i,h),
      tileAt(t1, a), tileAt(t2, b), spaceAt(c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, f),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)],
     [spaceAt(a), tileAt(t1, b), tileAt(t2, c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, f),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)]).


prob(p02, 
     [upFrom(a,d), upFrom(b,e), upFrom(c,f),
      upFrom(d,g), upFrom(e,h), upFrom(f,i),
      downFrom(g,d), downFrom(h,e), downFrom(i,f),
      downFrom(d,a), downFrom(e,b), downFrom(f,c),
      leftFrom(a,b), leftFrom(b,c),
      leftFrom(d,e), leftFrom(e,f),
      leftFrom(g,h), leftFrom(h,i),
      rightFrom(b,a), rightFrom(c,b),
      rightFrom(e,d), rightFrom(f,e),
      rightFrom(h,g), rightFrom(i,h),
      tileAt(t1, a), tileAt(t2, b), spaceAt(f),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, c),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)],
     [spaceAt(a), tileAt(t1, b), tileAt(t2, c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, f),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)]).

prob(p10, 
     [upFrom(a,d), upFrom(b,e), upFrom(c,f),
      upFrom(d,g), upFrom(e,h), upFrom(f,i),
      downFrom(g,d), downFrom(h,e), downFrom(i,f),
      downFrom(d,a), downFrom(e,b), downFrom(f,c),
      leftFrom(a,b), leftFrom(b,c),
      leftFrom(d,e), leftFrom(e,f),
      leftFrom(g,h), leftFrom(h,i),
      rightFrom(b,a), rightFrom(c,b),
      rightFrom(e,d), rightFrom(f,e),
      rightFrom(h,g), rightFrom(i,h),
      tileAt(t1, a), tileAt(t2, b), spaceAt(e),
      tileAt(t3,d), tileAt(t4,f), tileAt(t5, c),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)],
     [spaceAt(a), tileAt(t1, b), tileAt(t2, c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, f),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)]).

prob(p11, 
     [upFrom(a,d), upFrom(b,e), upFrom(c,f),
      upFrom(d,g), upFrom(e,h), upFrom(f,i),
      downFrom(g,d), downFrom(h,e), downFrom(i,f),
      downFrom(d,a), downFrom(e,b), downFrom(f,c),
      leftFrom(a,b), leftFrom(b,c),
      leftFrom(d,e), leftFrom(e,f),
      leftFrom(g,h), leftFrom(h,i),
      rightFrom(b,a), rightFrom(c,b),
      rightFrom(e,d), rightFrom(f,e),
      rightFrom(h,g), rightFrom(i,h),
      tileAt(t1, i), tileAt(t2, b), spaceAt(e),
      tileAt(t3,d), tileAt(t4,f), tileAt(t5, c),
      tileAt(t6, h), tileAt(t7, g), tileAt(t8, a)],
     [spaceAt(a), tileAt(t1, b), tileAt(t2, c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, f),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8, i)]).

prob(p20,
     [upFrom(a,d), upFrom(b,e), upFrom(c,f),
      upFrom(d,g), upFrom(e,h), upFrom(f,i),
      downFrom(g,d), downFrom(h,e), downFrom(i,f),
      downFrom(d,a), downFrom(e,b), downFrom(f,c),
      leftFrom(a,b), leftFrom(b,c),
      leftFrom(d,e), leftFrom(e,f),
      leftFrom(g,h), leftFrom(h,i),
      rightFrom(b,a), rightFrom(c,b),
      rightFrom(e,d), rightFrom(f,e),
      rightFrom(h,g), rightFrom(i,h),
      tileAt(t1,a), tileAt(t8,b), tileAt(t2,c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5,f),
      tileAt(t6,g), tileAt(t7,h), spaceAt(i)],
     [spaceAt(a), tileAt(t1, b), tileAt(t2, c),
      tileAt(t3,d), tileAt(t4,e), tileAt(t5, f),
      tileAt(t6, g), tileAt(t7, h), tileAt(t8,i)]).
